from typing import List

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from uuid import UUID
from books_app.core.database_books import SessionLocal
from books_app.models.book import BookModel
from books_app.routers.auth import require_role, get_current_user
from books_app.schemas.book import Book, BookCreate, BookUpdate, BooksResponse
from books_app.utils.normalize import normalize

router = APIRouter(prefix="/books", tags=["Books"])


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# ----- GET with pagination -----
@router.get("/", response_model=BooksResponse)
def get_books(
        db: Session = Depends(get_db),
        page: int = Query(1, ge=1),
        limit: int = Query(10, ge=1, le=50),
        current_user=Depends(get_current_user)
):
    offset = (page - 1) * limit

    total = db.query(BookModel).count()  # total number of books

    books = db.query(BookModel).offset(offset).limit(limit).all()

    return BooksResponse(
        total=total,
        items=books
    )


# ----- Search -----
@router.get("/search/{title}", response_model=list[Book])
def search_books(title: str, db: Session = Depends(get_db),
                 # current_user = Depends(get_current_user)
                 ):
    normalized_query = normalize(title)

    books = db.query(BookModel).all()
    results = [b for b in books if normalized_query in normalize(b.title)]

    if not results:
        raise HTTPException(status_code=404, detail="No books found matching title")

    return results


# ----- Create -----
@router.post("/", response_model=Book)
def create_book(book: BookCreate, db: Session = Depends(get_db)):
    new_book = BookModel(**book.dict())
    db.add(new_book)
    db.commit()
    db.refresh(new_book)
    return new_book


@router.post("/books/batch", response_model=List[Book])
def create_multiple_books(books: List[BookCreate], db: Session = Depends(get_db),
                          # current_user=Depends(require_role("admin"))
                          ):
    db_books = []
    created_books = []

    for book_create in books:
        # No need to check ID duplicates since it's autogenerated here
        db_book = BookModel(**book_create.dict())
        db_books.append(db_book)

    db.add_all(db_books)
    db.commit()

    return created_books


# ----- Update -----
@router.put("/{book_id}", response_model=Book)
def update_book(book_id: UUID, data: BookUpdate, db: Session = Depends(get_db),
                # current_user=Depends(require_role("admin"))
                ):
    book = db.query(BookModel).filter(BookModel.id == str(book_id)).first()
    if not book:
        raise HTTPException(status_code=404, detail="Book not found")

    for field, value in data.dict(exclude_unset=True).items():
        setattr(book, field, value)

    db.commit()
    db.refresh(book)
    return book


# ----- Delete -----
@router.delete("/{book_id}")
def delete_book(book_id: UUID, db: Session = Depends(get_db),
                # current_user=Depends(require_role("admin"))
                ):
    book = db.query(BookModel).filter(BookModel.id == str(book_id)).first()
    if not book:
        raise HTTPException(status_code=404, detail="Book not found")

    db.delete(book)
    db.commit()
    return {"message": "Book deleted successfully"}
